language: 'node_js'
node_js: '8'

before_script:
  - npm run generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  repo: aya-experience/aya-day-weather-app
  target_branch: gh-pages
  on:
    branch: master
