language: 'node_js'
node_js: '8'

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - master

before_script:
  - npm run lint
  - git clone https://github.com/aya-experience/aya-day-weather-proxy.git
  - cd aya-day-weather-proxy && API_KEY=$API_KEY node index.js & && cd ..
  - npm install
  - npm run generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  repo: aya-experience/aya-day-weather-app
  target_branch: gh-pages
  on:
    branch: master
