language: 'node_js'
node_js: '8'

cache:
  directories:
    - 'node_modules'

before_script:
  - npm run build
  - npm run lint
  - git clone https://github.com/aya-experience/aya-day-weather-proxy.git
  - cd aya-day-weather-proxy
  - npm ci
  - API_KEY=$API_KEY node index.js &
  - cd ..
  - npm run generate

notifications:
  email: false

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  repo: aya-experience/aya-day-weather-app
  target_branch: gh-pages
  fqdn: weather.zenika.com
  on:
    branch: master
